### ISSUE TITLE
Quoted extras value causes container Agent JVM to fail booting.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/hyperfoil-operator#17]
Using the extras configuration option for an agent works as expected with 1 property that is not wrapped with quotes.
`extras: -Dlog4j2.debug=true `

As soon as quoting is introduced to define 1 or more properties eg
`extras: " -Dlog4j2.debug=true " `
`extras: " -Dlog4j2.debug=true -Dfoo=bar " `
the agent JVM fails to boot correctly. Reporting this log message
```
Error: Could not find or load main class 
Caused by: java.lang.ClassNotFoundException: 
```
This might be explained by the incorrect translation of the extras value to the constructed container command line. Looking at the yaml specification the above 2 properties are defined as follows
```
spec:
  containers:
  - command:
    - java
    - -Djava.net.preferIPv4Stack=true
    - -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory
    - -Dio.hyperfoil.agent.name=agent-one
    - -Dio.hyperfoil.runid=0023
    - -Dio.hyperfoil.controller.cluster.ip=xxx.xxx.xxx.xxx
    - -Dio.hyperfoil.controller.cluster.port=7800
    - ""
    - -Dlog4j2.debug=true
    - ""
    - -Dfoo=bar
    - -cp
    - /deployment/lib/*:/deployment/extensions/*
    - io.hyperfoil.Hyperfoil$Agent
```
