### ISSUE TITLE
Operator 0.24.2 agents fail at deploying documented benchmark unless `.spec.version`is set to 0.24.2

### ISSUE THREAD

**Issue by fabiobrz** [Hyperfoil/hyperfoil-operator#18]
We've been installing the Hyperfoil operator on our cluster. The installation reported status is green.
The operator version which is installed is forced to be 0.24.2, as per the only existing (default channel), but the Hyperfoil runtime version run by the operator controller pod, or when creating `Hyperfoil` CRs, is actually 0.25.2 (latest).
The operator controller pod reports a ready status:
```
apiVersion: hyperfoil.io/v1alpha2
kind: Hyperfoil
metadata:
  creationTimestamp: '2023-09-20T08:37:08Z'
  generation: 1
  ...
spec:
  version: latest
status:
  lastUpdate: '2023-09-20T08:46:25Z'
  reason: Reconciliation succeeded.
  status: Ready
```
Now the issue, when uploading and running a [documented benchmark](https://hyperfoil.io/quickstart/quickstart7.html) via the WebCLI, two agents are started with ready status, but the controller is reporting the following error with the run being terminated after a few seconds:

```
[hyperfoil]$ uploadLoaded benchmark template k8s-hello-world with these parameters (with defaults): NAME      DEFAULT             CURRENT (CONTEXT)HOST_URL  (no default value)  http://hyperfoil:8090Uploading...Benchmark k8s-hello-world uploaded.[hyperfoil]$ run -d "Hello World Benchmark" -PHOST_URL=http://hyperfoil:8090 k8s-hello-worldStarted run 0001Run 0001, benchmark k8s-hello-worldHello World BenchmarkAgents: agent-one[STARTING], agent-two[STARTING]Terminated: 2023/09/20 08:49:20.965NAME  STATUS  STARTED  REMAINING  COMPLETED  TOTAL DURATION  DESCRIPTIONErrors:agent-two: Failed to start agent: com/fasterxml/jackson/core/exc/StreamConstraintsException: com.fasterxml.jackson.core.exc.StreamConstraintsExceptionagent-one: Failed to start agent: com/fasterxml/jackson/core/exc/StreamConstraintsException: com.fasterxml.jackson.core.exc.StreamConstraintsException
```

**Workaround**

* Create CRs with `spec.version: 0.24.2`
This happens because of some jackson artifacts classpath issue with the latest (0.25.2) version, which the `Hyperfoil` CR is using by default for some wrong reason, while [it is documented it should match the operator version instead](https://github.com/Hyperfoil/hyperfoil-operator/blob/master/config/crd/bases/hyperfoil.io_hyperfoils.yaml#L142).
