### ISSUE TITLE
How to Install Hyperfoil operator 0.19

### ISSUE THREAD

**Issue by pierDipi** [Hyperfoil/hyperfoil-operator#3]
I'm installing the Hyperfoil operator using a subscription (that should install the latest available version)
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hyperfoil-bundle
  namespace: openshift-operators
spec:
  channel: alpha
  name: hyperfoil-bundle
  source: community-operators
  sourceNamespace: openshift-marketplace
```
The version that I get is 0.15.1
![image](https://user-images.githubusercontent.com/33736985/162975126-6bf7d94d-301f-4e36-aac2-6d6d887a07dd.png)

I see that there is Hyperfoil 0.19 on quay https://quay.io/repository/hyperfoil/hyperfoil?tab=tags&tag=latest but I still get 0.15.1

Is there any way to install Hyperfoil operator 0.19? is it actually released?

**Comment by pierDipi** [comment]
Thanks @rvansa!

I see, it's using `latest`

```yaml
  containerStatuses:
  - containerID: cri-o://b458d5508c58a7dba11f711b17e2cb89e73a8bfc0de00cdf40890789e21f4c4d
    image: quay.io/hyperfoil/hyperfoil:latest
    imageID: quay.io/hyperfoil/hyperfoil@sha256:ce258eba6a1f29e7f08f93320b7beb919c78eebc8556a8a9030e9fbc5365d624
```
